---
# where to run the ci/cd pipeline
pool:
  vmImage: ubuntu-22.04

# when to run
trigger:
  - main

# what has to be done
steps:
  - task: Docker@2
    inputs:
      command: build
      Dockerfile: "./Dockerfile"
      repository: 'shivakrishna99/saleordashboard:AZDEV'
      tags: "latest"
  - task: Docker@2
    inputs:
      command: push
      repository: 'shivakrishna99/saleordashboard:AZDEV'
      tags: "latest"
      containerRegistry: 'Docker-Hub-Connection'

