---
pool:
  vmImage: ubuntu-22.04
trigger:
  - main
steps:
  - task: Docker@2
    inputs:
      command: build
      Dockerfile: ./Dockerfile
      repository: shivakrishna99/saleordashboard:AZDEV
      tags: my-repo:latest
  - task: Docker@2
    inputs:
      command: push
      repository: shivakrishna99/saleordashboard:AZDEV
      tags: my-repo:latest
      containerRegistry: Docker-Hub-Connection

