---
# where to run the ci/cd pipeline
pool:
  vmImage: ubuntu-22.04

# when to run
trigger:
  - main

# what has to be done
steps:
  - task: Docker@2
    inputs:
      command: build
      Dockerfile: "./Dockerfile"
      tags: "shivakrishna99/saleordashboard:AZDEV"

  - task: Docker@2
    inputs:
      command: push
      tags: "shivakrishna99/saleordashboard:AZDEV"
      containerRegistry: Docker-Hub-Connection

